### ISSUE TITLE
Add problem main view

### ISSUE THREAD

**Issue by ITsvetkoFF** [ITsvetkoFF/Kv-009#43]
- [x] view using guidelines
- [x] add photo functionality
- [x] send problem to server

**Comment by daniiltyshchenko** [comment]
- [x] merge addProblem & addPhoto functionality
- [x] AddProblemFragment refactoring
- [x] fix fabCancelButton when mapView inflating
- [x] fix FAB’s at API 15 (square-behavior) - Google’s bug, will be fixed with DSL next version
- [x] fix fabAdd when swiping snack bar
- [x] spinner view upgrade
- [x] move to static snack bars
- [x] android.support.design.widget.TextInputLayout for EditTexts at xml
- [x] input data validation and errors snack bars making
- [x] upgrade design for add problem view
- [x] add «next» and «done» buttons to keyboard / or retain multiline
- [x] checking internet connection
- [ ] exit from AddProblemFragment when problem added to server
- [x] change color for fabCancel
- [ ] screen rotation
- [x] allHardcode.toString();
- [x] change snack bar Action text color
